name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^6.1.1
  go_router: ^14.0.0
  # Firebase packages
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Testing dependencies
  mockito: ^5.4.4
  build_runner: ^2.4.8
  fake_cloud_firestore: ^3.0.3
  firebase_auth_mocks: ^0.14.1
  firebase_core_platform_interface: ^6.0.2

flutter:
  uses-material-design: true
  
  # Assets configuration
  assets:
    - assets/images/products/
    - assets/images/collections/
    - assets/images/carousel/